# Generated by Django 5.0.6 on 2024-07-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classe',
            table='classe',
        ),
        migrations.AlterModelTable(
            name='classpack',
            table='classpack',
        ),
        migrations.AlterModelTable(
            name='classpackclasse',
            table='classpackclasse',
        ),
        migrations.AlterModelTable(
            name='classpackdiscountrules',
            table='classpackdiscountrule',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollment',
        ),
        migrations.AlterModelTable(
            name='instrument',
            table='instrument',
        ),
        migrations.AlterModelTable(
            name='level',
            table='level',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
        migrations.AlterModelTable(
            name='teacherclasse',
            table='teacherclasse',
        ),
    ]
