# Generated by Django 5.0.6 on 2024-07-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_classes_classe_rename_enrollments_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
